version: '3.5'

services:

  backend:
    build: ./backend
    image: autosubs_backend
    depends_on:
      - freeling
    networks:
      - my-network

  frontend:
    build: ./frontend
    image: autosubs_frontend
    depends_on:
      - backend  # Indica que el frontend depende del backend
    ports:
      - "5000:5000"  # Puertos para acceder al frontend
      #host:container
    #extra_hosts:
    #  - "autosubs.es:172.19.0.3"
    networks:
      - my-network
  
  freeling:
    build: ./backend/freeling
    image: autosubs_backend_freeling
    networks:
      - my-network


    
networks:
  my-network:
    driver: bridge

