version: '3'

services:

  backend:
    build: ./backend
    image: autosubs_backend
    networks:
      - my-network

  frontend:
    build: ./frontend
    image: autosubs_frontend
    depends_on:
      - backend  # Indica que el frontend depende del backend
    #ports:
    #  - "5000:5000"  # Puertos para acceder al frontend
    networks:
      - my-network
    
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
