
services:

  backend:
    build: ./backend
    image: autosubs_backend
    depends_on:
      freeling:
        condition: service_healthy
    networks:
      - my-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://backend:6001/healthcheck || exit 1
      interval: 25s
      retries: 10
      start_period: 20s
      timeout: 10s


  frontend:
    build: ./frontend
    image: autosubs_frontend
    depends_on:
      backend:  # Indica que el frontend depende del backend
        condition: service_healthy
    ports:
      - "5000:5000"  # Puertos para acceder al frontend
    networks:
      - my-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://frontend:5000/healthcheck || exit 1
      interval: 25s
      retries: 10
      start_period: 20s
      timeout: 10s

  
  freeling:
    build: ./backend/freeling
    image: autosubs_backend_freeling
    networks:
      - my-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://freeling:7002/healthcheck || exit 1
      interval: 15s
      retries: 10
      start_period: 10s
      timeout: 10s


    
networks:
  my-network:
    driver: bridge

