version: '3'

services:

  backend:
    build: ./backend
    image: autosubs_backend
    networks:
      - my-network

  frontend:
    build: ./frontend
    image: autosubs_frontend
    depends_on:
      - backend  # Indica que el frontend depende del backend
    ports:
      - "80:5000"  # Puertos para acceder al frontend
      #host:container
    #extra_hosts:
    #  - "autosubs.es:172.19.0.3"
    networks:
      - my-network
  


    
networks:
  my-network:
    driver: bridge

